export const categories = [
  'Dating',
  'Friendship',
  'Open Relationships',
  'Business Relationships',
  'Virginity',
  'Friends with Benefits',
  'Age Gaps',
  'Marriage Issues',
  'Working Relationships',
  'Texting',
  'Perseverance',
  'Negotiation',
  'P.U.A.',
  'Needy Behavior',
  'Moving On',
  'Falling in Love',
  'Infidelity',
  'Interracial',
  'Finding the Right Person',
  'How to Get a Relationship?',
  'Health',
  'Get Back Your Ex',
  'Friends Zone',
  'Disrespectful',
  'Distant Lover',
  'Depression',
  'Courtship',
  'Confidence',
  'Being too Nice',
  'Physical Abuse',
  'Emotional Abuse',
  'Verbal Abuse',
]
