export const categories = [
  'Dating',
  'Friendship',
  'Open Relationships',
  'Business Relationships',
  'Virginity',
  'Friends with Benefits',
  'Age Gaps',
  'Marriage Issues',
  'Work Relationships',
  'Texting',
  'Perseverance',
  'Negotiation',
  'Moving On',
  'Falling in Love',
  'Infidelity',
  'Interracial',
  'Get Back Your Ex',
  'Friends Zone',
  'Disrespect',
  'Distant Lover',
  'Depression',
  'Being Too Nice',
  'Physical Abuse',
  'Emotional Abuse',
  'Verbal Abuse',
  'Tinder Tales',
  'Simping Tales',
  'Break Up'
]
